"""Added new tables

Revision ID: 3befe371eb74
Revises: 8b9c2705dede
Create Date: 2018-11-24 01:54:40.422032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3befe371eb74'
down_revision = '8b9c2705dede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardengroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('short_name', sa.UnicodeText(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_gardengroup_organisation_id_organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gardengroup')),
    sa.UniqueConstraint('slug', name=op.f('uq_gardengroup_slug'))
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gardengroup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('year_in', sa.Date(), nullable=True),
    sa.Column('year_out', sa.Date(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gardengroup_id'], ['gardengroup.id'], name=op.f('fk_group_gardengroup_id_gardengroup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('slug', name=op.f('uq_group_slug'))
    )
    op.alter_column('organisation', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_table('group')
    op.drop_table('gardengroup')
    # ### end Alembic commands ###
